services:
  # 数据库
  postgres:
    image: postgres:latest
    container_name: console-db
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres-data:/var/lib/postgresql
    restart: unless-stopped

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: console-server
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     DATABASE_URL: "postgresql+asyncpg://postgres:123456@postgres:5432/test001"
  #     CORS_ALLOW_ORIGIN: "*"
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped